relativeURLs = true
googleAnalytics = "UA-159072578-1"
title = "Hui Li"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]

[author]
name = "Hui Li"

[markup] # needed to add html in .md
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
title = "PH.D. Candidate"
institution = "Department at School of Finance, Renmin University of China"
Twitter = ""
Email = "lihuieco@ruc.edu.cn"
