relativeURLs = true
googleAnalytics = "UA-159072578-1"
title = "Zhonghua Wang"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]

[author]
name = "Zhonghua Wang"
homepage = "https://huili.netlify.app/"

[params]
institution = "School of Finance, Renmin University of China"
shortbio = "Ph.D. candidate in Economics"
logo = ""
Email = "18401688233@163.com"

[markup]
  [markup.highlight]
    style = "solarized-light"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
